#!/usr/bin/env zunit
#{{{                    MARK:Header
#**************************************************************
##### Purpose: kubectl-aliases contract pins. The .kubectl_aliases
#####          file is GENERATED by generate_aliases.py, so contract
#####          tests guard against renames during regeneration AND
#####          against the plugin entry point silently failing on
#####          path lookup.
#}}}***********************************************************

@setup {
    0="${${0:#$ZSH_ARGZERO}:-${(%):-%N}}"
    0="${${(M)0:#/*}:-$PWD/$0}"
    pluginDir="${0:h:A}"
    aliasFile="$pluginDir/.kubectl_aliases"
}

@test 'plugin script sources .kubectl_aliases adjacent to itself via \${0:h}' {
    # Pin: lookup must be relative to the plugin file, not $PWD.
    # The zsh plugin standard preamble + ${0:h} is what makes the
    # plugin work under any plugin manager.
    local body
    body=$(cat "$pluginDir/kubectl-aliases.plugin.zsh")
    assert "$body" contains '${0:h}/.kubectl_aliases'
    assert "$body" contains 'source $aliasesFile'
}

@test 'plugin script errors loudly when .kubectl_aliases is missing' {
    # Without this branch a broken install would silently produce a
    # kubectl-less shell. Pin the stderr branch.
    local body
    body=$(cat "$pluginDir/kubectl-aliases.plugin.zsh")
    assert "$body" contains 'ERROR'
    assert "$body" contains '>&2'
}

@test 'generated alias file exists and is non-empty' {
    # Pin: the generated file must ship in the repo (CI must not
    # regenerate at install time — too many users on read-only roots).
    assert "$aliasFile" is_file
    local size
    size=$(wc -c < "$aliasFile" | tr -d ' ')
    local result=$([[ "$size" -gt 0 ]] && echo yes || echo "no:$size")
    assert "$result" same_as 'yes'
}

@test 'generated alias file declares 700+ aliases (catastrophic-shrink guard)' {
    # If a future generator regression drops the count below 700, the
    # generator has lost a verb/flag matrix. Pin a floor far enough
    # below current (~790) that legitimate adds/removes don't flap.
    local count
    count=$(grep -c '^alias ' "$aliasFile")
    local result=$([[ "$count" -ge 700 ]] && echo yes || echo "no:$count")
    assert "$result" same_as 'yes'
}

@test 'k is the canonical 1-char shortcut for kubectl' {
    # Pin: if `k` ever stops being `kubectl`, every other alias built
    # off `k...` becomes a footgun.
    local body
    body=$(zsh -c "
        emulate zsh
        source '$pluginDir/kubectl-aliases.plugin.zsh'
        alias k
    ")
    assert "$body" same_as "k=kubectl"
}

@test 'kg is kubectl get (NOT kubectl get -A or kubectl get -o=yaml)' {
    # Pin: kg is the bare `get`; suffixes layer on (kgo=get -o,
    # kga=get --all-namespaces, kgw=get --watch).
    local body
    body=$(zsh -c "
        emulate zsh
        source '$pluginDir/kubectl-aliases.plugin.zsh'
        alias kg
    ")
    assert "$body" same_as "kg='kubectl get'"
}

@test 'kd is kubectl describe (NOT delete — that is krm)' {
    # Pin: highest-stakes name-collision risk in the whole plugin.
    # If kd ever resolves to delete, users lose pods on info commands.
    local body
    body=$(zsh -c "
        emulate zsh
        source '$pluginDir/kubectl-aliases.plugin.zsh'
        alias kd
    ")
    assert "$body" same_as "kd='kubectl describe'"
}

@test 'krm is kubectl delete (the only delete short form)' {
    local body
    body=$(zsh -c "
        emulate zsh
        source '$pluginDir/kubectl-aliases.plugin.zsh'
        alias krm
    ")
    assert "$body" same_as "krm='kubectl delete'"
}

@test 'kex is kubectl exec -i -t (an interactive TTY by default)' {
    # Pin: dropping -i or -t silently breaks `kex pod -- sh` into a
    # non-interactive exec that prints nothing.
    local body
    body=$(zsh -c "
        emulate zsh
        source '$pluginDir/kubectl-aliases.plugin.zsh'
        alias kex
    ")
    assert "$body" contains 'kubectl exec'
    assert "$body" contains '-i'
    assert "$body" contains '-t'
}

@test 'ka is kubectl apply --recursive -f (recursive by default)' {
    # Pin: --recursive must stay on `ka` so `ka manifests/` works on
    # nested charts. Dropping it would break common workflows silently.
    local body
    body=$(zsh -c "
        emulate zsh
        source '$pluginDir/kubectl-aliases.plugin.zsh'
        alias ka
    ")
    assert "$body" contains 'kubectl apply'
    assert "$body" contains '--recursive'
    assert "$body" contains '-f'
}

@test 'kgpo is kubectl get pods (resource shortcut: pods -> po)' {
    local body
    body=$(zsh -c "
        emulate zsh
        source '$pluginDir/kubectl-aliases.plugin.zsh'
        alias kgpo
    ")
    assert "$body" same_as "kgpo='kubectl get pods'"
}

@test 'kgdep is kubectl get deployment (NOT deployments plural)' {
    # Generator uses singular for matrix alignment. Pin so a refactor
    # to plural doesn't quietly rename the entire deployment family.
    local body
    body=$(zsh -c "
        emulate zsh
        source '$pluginDir/kubectl-aliases.plugin.zsh'
        alias kgdep
    ")
    assert "$body" same_as "kgdep='kubectl get deployment'"
}

@test 'kgsvc is kubectl get service (singular)' {
    local body
    body=$(zsh -c "
        emulate zsh
        source '$pluginDir/kubectl-aliases.plugin.zsh'
        alias kgsvc
    ")
    assert "$body" same_as "kgsvc='kubectl get service'"
}

@test 'output suffixes — oyaml = -o=yaml, ojson = -o=json (KEY=value form)' {
    # Pin: the generator uses `-o=yaml` (with equals), NOT `-o yaml`
    # (space). Both work for kubectl but pipelines may parse differently.
    local yaml json
    yaml=$(zsh -c "
        emulate zsh
        source '$pluginDir/kubectl-aliases.plugin.zsh'
        alias kgpooyaml
    ")
    json=$(zsh -c "
        emulate zsh
        source '$pluginDir/kubectl-aliases.plugin.zsh'
        alias kgpoojson
    ")
    assert "$yaml" contains '-o=yaml'
    assert "$json" contains '-o=json'
}

@test 'watch suffix w appends --watch (NOT --watch-only)' {
    # Pin: --watch streams updates after current state; --watch-only
    # skips current state. Generator chose --watch — pin it.
    local body
    body=$(zsh -c "
        emulate zsh
        source '$pluginDir/kubectl-aliases.plugin.zsh'
        alias kgpow
    ")
    assert "$body" contains '--watch'
    assert "$body" contains 'kubectl get pods'
}

@test 'all-namespaces suffix all expands to --all-namespaces (NOT -A)' {
    # Pin: kubectl accepts both -A and --all-namespaces; generator
    # picked the long form. Pin to catch a refactor to -A.
    local body
    body=$(zsh -c "
        emulate zsh
        source '$pluginDir/kubectl-aliases.plugin.zsh'
        alias kgpoallw
    ")
    assert "$body" contains '--all-namespaces'
    assert "$body" contains '--watch'
}

@test 'kube-system prefix ksys expands to --namespace=kube-system' {
    # Pin: kube-system convenience prefix must keep the literal name.
    # If a refactor moved it to a $KUBE_SYSTEM_NS variable, expansion
    # would happen at source time and burn into the alias.
    local body
    body=$(zsh -c "
        emulate zsh
        source '$pluginDir/kubectl-aliases.plugin.zsh'
        alias ksysgpow
    ")
    assert "$body" contains '--namespace=kube-system'
    assert "$body" contains '--watch'
}

@test 'sourcing the plugin defines >700 aliases at runtime' {
    # End-to-end: prove the plugin actually populates aliases when
    # sourced — not just that the file has them.
    local count
    count=$(zsh -c "
        emulate zsh
        source '$pluginDir/kubectl-aliases.plugin.zsh'
        alias | wc -l
    " | tr -d ' ')
    local result=$([[ "$count" -ge 700 ]] && echo yes || echo "no:$count")
    assert "$result" same_as 'yes'
}

@test 're-sourcing the plugin is idempotent (alias count stable)' {
    # Pin: sourcing twice must not double-count or print warnings.
    local first second
    first=$(zsh -c "
        emulate zsh
        source '$pluginDir/kubectl-aliases.plugin.zsh'
        alias | wc -l
    " | tr -d ' ')
    second=$(zsh -c "
        emulate zsh
        source '$pluginDir/kubectl-aliases.plugin.zsh'
        source '$pluginDir/kubectl-aliases.plugin.zsh'
        alias | wc -l
    " | tr -d ' ')
    assert "$first" same_as "$second"
}

@test 'generate_aliases.py exists and is executable (regeneration path live)' {
    # Pin: the generator is the source of truth. If it disappears,
    # nobody can regenerate after a kubectl flag change.
    assert "$pluginDir/generate_aliases.py" is_file
    [[ -x "$pluginDir/generate_aliases.py" ]]
    assert $? equals 0
}
